[package]
name = "event-bus"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
async-nats = "0.33"
tokio = { version = "1", features = ["sync", "rt"] }
futures = "0.3"
thiserror = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-stream = "0.3"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
tokio-test = "0.4"
