[package]
name = "auth-rs"
version = "1.0.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }

sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "uuid", "chrono"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

dotenvy = "0.15"

jsonwebtoken = "9"
argon2 = "0.5"

rand = "0.8"
sha2 = "0.10"
hex = "0.4"

rsa = "0.9"
base64 = "0.22"

async-nats = "0.33"

tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "cors"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

jsonschema = "0.18"
once_cell = "1.19"

dashmap = "6"
governor = "0.6"
tower_governor = "0.8"
prometheus = "0.13"
